<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="specificationlayout" nsURI="http://specificationlayout" nsPrefix="specificationlayout">
  <eAnnotations source="http://www.w3.org/2002/07/owl#Ontology">
    <details key="uri" value="http://specificationlayout"/>
    <details key="prefix" value="specificationlayout"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Header">
    <eAnnotations source="http://www.w3.org/2002/07/owl#Class">
      <details key="uri" value="http://specificationlayout#Header"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headlineRight">
      <eAnnotations source="http://www.w3.org/2002/07/owl#DatatypeProperty">
        <details key="uri" value="http://specificationlayout#headlineRight"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author">
      <eAnnotations source="http://www.w3.org/2002/07/owl#DatatypeProperty">
        <details key="uri" value="http://specificationlayout#author"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footerRight">
      <eAnnotations source="http://www.w3.org/2002/07/owl#DatatypeProperty">
        <details key="uri" value="http://specificationlayout#footerRight"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date">
      <eAnnotations source="http://www.w3.org/2002/07/owl#DatatypeProperty">
        <details key="uri" value="http://specificationlayout#date"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableOfConents">
      <eAnnotations source="http://www.w3.org/2002/07/owl#DatatypeProperty">
        <details key="uri" value="http://specificationlayout#tableOfConents"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footerLeft">
      <eAnnotations source="http://www.w3.org/2002/07/owl#DatatypeProperty">
        <details key="uri" value="http://specificationlayout#footerLeft"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title">
      <eAnnotations source="http://www.w3.org/2002/07/owl#DatatypeProperty">
        <details key="uri" value="http://specificationlayout#title"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footerCenter">
      <eAnnotations source="http://www.w3.org/2002/07/owl#DatatypeProperty">
        <details key="uri" value="http://specificationlayout#footerCenter"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headlineCenter">
      <eAnnotations source="http://www.w3.org/2002/07/owl#DatatypeProperty">
        <details key="uri" value="http://specificationlayout#headlineCenter"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document">
    <eAnnotations source="http://www.w3.org/2002/07/owl#Class">
      <details key="uri" value="http://specificationlayout#Document"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" eType="//Header">
      <eAnnotations source="http://www.w3.org/2002/07/owl#ObjectProperty">
        <details key="uri" value="http://specificationlayout#header"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootElement">
      <eAnnotations source="http://www.w3.org/2002/07/owl#ObjectProperty">
        <details key="uri" value="http://specificationlayout#rootElement"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
